# 73 глагола Греты по 7 частям: (инфинитив, перевод, Perfekt)
VERBS=[
[('beginnen','начинать(ся)','hat begonnen'),('bekommen','получать','hat bekommen'),
 ('verstehen','понимать','hat verstanden'),('vermuten','предполагать','hat vermutet'),
 ('überlegen','обдумывать','hat überlegt'),('beachten','обращать внимание','hat beachtet'),
 ('benutzen','пользоваться','hat benutzt'),('verlieren','терять','hat verloren'),
 ('entdecken','обнаруживать','hat entdeckt'),('benennen','называть','hat benannt'),
 ('erleben','переживать','hat erlebt')],
[('vermeiden','избегать','hat vermieden'),('ermöglichen','давать возможность','hat ermöglicht'),
 ('gehören','принадлежать','hat gehört'),('erfinden','изобретать','hat erfunden'),
 ('verbessern','улучшать','hat verbessert'),('übersiedeln','переселяться','ist übersiedelt'),
 ('bedeuten','значить','hat bedeutet'),('verfassen','писать (текст)','hat verfasst'),
 ('unterschreiben','подписывать','hat unterschrieben'),('verschicken','отправлять','hat verschickt')],
[('beantworten','отвечать на','hat beantwortet'),('verabreden','договариваться','hat verabredet'),
 ('vereinbaren','согласовывать','hat vereinbart'),('übernehmen','брать на себя','hat übernommen'),
 ('unterstützen','поддерживать','hat unterstützt'),('verstärken','укреплять','hat verstärkt'),
 ('begrüßen','приветствовать','hat begrüßt'),('umarmen','обнимать','hat umarmt'),
 ('verschieben','переносить','hat verschoben'),('verpassen','пропускать','hat verpasst')],
[('besuchen','навещать','hat besucht'),('betreuen','присматривать','hat betreut'),
 ('erlauben','разрешать','hat erlaubt'),('erteilen','давать (поручение)','hat erteilt'),
 ('beobachten','наблюдать','hat beobachtet'),('beraten','консультировать','hat beraten'),
 ('erzählen','рассказывать','hat erzählt'),('vertiefen','углубляться','hat vertieft'),
 ('verlieben','влюбляться','hat verliebt'),('vermitteln','передавать (другому)','hat vermittelt')],
[('erklären','объяснять','hat erklärt'),('wiederholen','повторять','hat wiederholt'),
 ('bestellen','заказывать','hat bestellt'),('empfehlen','рекомендовать','hat empfohlen'),
 ('verkaufen','продавать','hat verkauft'),('vergleichen','сравнивать','hat verglichen'),
 ('bewerten','оценивать','hat bewertet'),('berühren','трогать','hat berührt'),
 ('überprüfen','проверять','hat überprüft'),('verwenden','использовать','hat verwendet'),
 ('bezahlen','платить','hat bezahlt')],
[('gewinnen','выигрывать','hat gewonnen'),('bedanken','благодарить (sich)','hat bedankt'),
 ('behalten','оставить себе','hat behalten'),('verbinden','соединять','hat verbunden'),
 ('gefallen','нравиться','hat gefallen'),('enthalten','содержать','hat enthalten'),
 ('beschreiben','описывать','hat beschrieben'),('berichten','сообщать','hat berichtet'),
 ('verbieten','запрещать','hat verboten'),('ergänzen','дополнять','hat ergänzt'),
 ('übernachten','ночевать','hat übernachtet')],
[('umkreisen','обводить кружком','hat umkreist'),('bezeichnen','обозначать','hat bezeichnet'),
 ('unterstreichen','подчёркивать','hat unterstrichen'),('erledigen','улаживать','hat erledigt'),
 ('verabschieden','прощаться (sich)','hat verabschiedet'),('bestehen','выдержать','hat bestanden'),
 ('versuchen','пытаться','hat versucht'),('verdienen','зарабатывать','hat verdient'),
 ('vermissen','скучать по','hat vermisst'),('vergessen','забывать','hat vergessen')],
]
